[versions]
coroutines_version = "1.6.4"
ktor_version = "2.1.3"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines_version" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor_version" }
ktor-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor_version" }
ktor-engine-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor_version" }
ktor-engine-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor_version" }
ktor-plugin-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor_version" }
ktor-plugin-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor_version" }
ktor-plugin-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor_version" }

[bundles]
ktor-common = [
    "ktor-core",
    "ktor-plugin-contentnegotiation",
    "ktor-plugin-serialization",
    "ktor-plugin-logging"
]

[plugins]
